env:
  commonjs: true
  es6: true
  node: true
  jest: true
globals:
  window: true
extends: 'airbnb'
parser: 'babel-eslint'
parserOptions:
  ecmaFeatures:
    jsx: true
    impliedStrict: true,
    classes: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
  - react-hooks
rules:
  arrow-parens: 0
  no-console: 2
  semi: 0
  object-curly-spacing: 0
  react-hooks/rules-of-hooks: 'error'
  react-hooks/exhaustive-deps: 'warn'
  react/jsx-filename-extension: 0
  indent: 0
  comma-dangle: 0
  eol-last: 0
