version: "3"
services:
  backend:
    build: ./backend
    container_name: chat-lgh-backend-prod
    depends_on:
      - postgres
    ports:
      - 3000:3000
    env_file:
     - ./backend/src/env/production.env
  postgres:
    build: ./postgres
    env_file:
     - ./backend/src/env/production.env
    volumes:
      - chat-lgh-postgres-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
volumes:
  chat-lgh-postgres-data: