version: "3"
services:
  backend:
    container_name: chat-lgh-backend-dev
    build:
      context: ./backend
      dockerfile: Dockerfile-dev
    volumes:
      - chat-lgh-backend-sync:/app:nocopy
    env_file:
     - ./backend/src/env/development.env
  postgres:
    env_file:
     - ./backend/src/env/development.env
volumes:
  chat-lgh-backend-sync:
    external: true