version: "3"
services:
  backend:
    container_name: chat-backend-dev
    build:
      context: ./backend
      dockerfile: Dockerfile-dev
    volumes:
      - backend-sync:/app:nocopy
    environment:
      - NODE_ENV=development
volumes:
  backend-sync:
    external: true